# Generated by Django 2.2.3 on 2019-07-30 12:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0003_auto_20190730_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritethings',
            name='audit_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='favoritethings',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
